name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Nodig om naar gh-pages te kunnen schrijven
permissions:
  contents: write
  pages: write
  id-token: write

# voorkom parallelle deploys
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      # Optie A (aanrader): docusaurus deploy — gebruikt config.organizationName/projectName/deploymentBranch
      - name: Deploy via Docusaurus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx docusaurus deploy
